// Code generated by go generate; DO NOT EDIT.
//go:build linux_bpf
// +build linux_bpf

package runtime

var RuntimeSecurity = NewRuntimeAsset("runtime-security.c", "b5ddb28ac4c046322ac89bd87c9ca0393b7c20393312efe8a352f4cf1b45914d")
