// Code generated by go generate; DO NOT EDIT.
//go:build linux_bpf
// +build linux_bpf

package runtime

var RuntimeSecurity = NewRuntimeAsset("runtime-security.c", "e8648c2972a0cca267edd4c8013b92dfb77f4a265305a33bac45647eb1157e7d")
