// Code generated by go generate; DO NOT EDIT.
//go:build linux_bpf
// +build linux_bpf

package runtime

var RuntimeSecurity = NewRuntimeAsset("runtime-security.c", "fb955543692f5f0f0aec91e73d9b1a7996b95ccc2ee934524f757118d7739d65")
